# Generated by Django 5.2.5 on 2025-08-29 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL para scraping')),
                ('css_selector', models.CharField(blank=True, help_text='Ex.: h1.title ou .price .value. Se vazio, envia o <title> da página', max_length=255, verbose_name='CSS Selector (opcional)')),
                ('token', models.CharField(max_length=200, verbose_name='Token do Bot Telegram')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Chat ID do Telegram')),
                ('schedule_time', models.TimeField(help_text='Horário local (America/Sao_Paulo)', verbose_name='Horário diário (HH:MM)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última execução')),
                ('last_message', models.TextField(blank=True, verbose_name='Última mensagem enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.bottask')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-ran_at'],
            },
        ),
    ]
